name: pull request

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - run: npm install

      - run: npm run lint

      - run: npm run test
